linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - golint
    - deadcode
    - goconst
    - unconvert
    - unparam
    - whitespace
    - ineffassign
    - exportloopref
    - staticcheck
    - unused
    - varcheck
    - misspell
